### ISSUE TITLE
Show more stats about zxtns when "Computing your transaction"

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragon#157]
It would be nice to see a z-op id and maybe how long we have waited for the tx to complete and then how long it took in total.

On a very busy computer, it seems to hang and this may cause users to try to send the transaction again, which I myself have done once already, before this popup window existed.

**Comment by leto** [comment]
This tx took over 30s and it would be better UI to give some kind of spinner/timer/etc to show the user something is happening:

```
    "id": "opid-daa8d7e5-6d3a-4c62-a4dc-09052b9e7b33",
    "status": "success",
    "creation_time": 1582937502,
    "result": {
      "txid": "69bcd447002c6708c3c800d881bff9cecb56eaf5ff5a88c4669c03f713cba797"
    },
    "execution_secs": 33.28702209,
    "method": "z_sendmany",
    "params": {
```

**Comment by DenioD** [comment]
https://github.com/MyHush/SilentDragon/commit/36a98d64b6bfc82572d3c1f3502791feacd6c8dc  done. I think this issue can be close
