### ISSUE TITLE
Desktop Icon Needs to be Fixed

### ISSUE THREAD

**Issue by UrgeyBergy** [MyHush/SilentDragon#176]
Currently SilentDragon has a wallet with the Hush logo on it as a desktop icon, this looks to have reverted from more recent version which had the SD logo. See attached image comparison.
![Capture1](https://user-images.githubusercontent.com/37842843/81024803-95c62d00-8e42-11ea-80e0-a68eaef00897.png)

**Comment by leto** [comment]
@UrgeyBergy which OS is this? The icon files are different for each OS

**Comment by UrgeyBergy** [comment]
> @UrgeyBergy which OS is this? The icon files are different for each OS

I'm looking at the 64bit windows release

**Comment by leto** [comment]
@UrgeyBergy will be fixed in next release, thanks @DenioD !!! :beers:
