### ISSUE TITLE
Updating hush3.conf RPC credentials enables core dump

### ISSUE THREAD

**Issue by csharpee** [MyHush/SilentDragon#180]
When someone changes SD config file RPC user/pass settings in .conf file _(.komodo/hush3/hush3.conf)_, then launches SD, SD asks for you to update the settings to connect to connect to hushd. 

**Settings example:** 
```
rpcuser=rpcuser
rpcpassword=rpcpass
```

When we click **edit --> settings** to update SD, it crashes and core dumps. Core dump logs below.

```
gdb silentdragon 
run 
bt
```
**Output:** 
https://gist.github.com/csharpee/57c68126a026b3c30c5f7a686033e2ad

**Comment by csharpee** [comment]
I tested rebuilding SD and launching to see if the config settings would be updated, but this did not provide a solution and produced same results as stated above. 

```
./build.sh clean
./build.sh
```

**Comment by csharpee** [comment]
Oops; after updating the configuration file I forgot to close `./src/hushd via ./src/hush-cli stop`. 
The **hushd** was still running producing **authentication** errors via hush daemon (server)...

By updating the config file while the hushd was running, forced me to CTRL-C hushd. 
This is bad practice to do and can potentially produce **wallet.dat** problems.

Overall, don't change a config file while hushd is running. Stop the hushd before, then update config, then relaunch hushd and SD. 

This bug ONLY applies to those running their own hush3 full node.

**Comment by leto** [comment]
Yes, changing a conf file while the full node is running, especially changing the password, can lead to bad stuff
