### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragon#3]
Which is shown when switching applications and as icons on the desktop

**Comment by leto** [comment]
We have this icon for now, we can make something fancier later:

![image](https://user-images.githubusercontent.com/30298/59354800-b2152480-8cda-11e9-9cb0-9b3fcd3f4e79.png)

This is the icon that shows when you are switching applications, there are still some other icons to update, but those are less important

**Comment by gilardh** [comment]
Or this one?

![hushWallet](https://user-images.githubusercontent.com/39105646/59357021-583c4b00-8d2a-11e9-8d3f-005f5602439d.png)

**Comment by leto** [comment]
@gilardh yours looks a lot nicer!!!! Obviously I am not a graphic designer 😅 

I will use yours, thanks!

**Comment by gilardh** [comment]
👍
