### ISSUE TITLE
SD icon on windows is not up to date

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragon#34]
The logo visible in the SilentDragon application is not up to date on Windows :
![20190722 Logo SD](https://user-images.githubusercontent.com/39105646/61598037-22875d80-ac18-11e9-9dc8-1037eb22a05c.jpg)

**Comment by leto** [comment]
@gilardh I think @FireMartZ fixed this in a commit after the 0.7.7 release, but I need to test that it isn't causing another bug on Mac

**Comment by leto** [comment]
this was finally fixed after much bloodshed
