### ISSUE TITLE
Could not create HUSH3.conf.

### ISSUE THREAD

**Issue by yusufsahinhamza** [MyHush/SilentDragon#55]
Im not sure why but last release SilentDragon couldn't create HUSH3.conf but when i compile it from source, HUSH3.conf created successfully.

**Comment by ismailtm** [comment]
Hi,

Can you provide the path to the release you used?
This might not be an issue at all and already resolved in the latest build.

**Comment by yusufsahinhamza** [comment]
@ismailtm 

SilentDragon 0.7.7, Windows x64

I don't know if it's resolved because i had this problem in the latest release but there is no problem when i compile it from source.

**Comment by leto** [comment]
@yusufsahinhamza this is a known problem with our current binaries, it's fixed in git.

One way to get around it, is create Appdata/Komodo, and that should prevent the bug.

**Comment by yusufsahinhamza** [comment]
@leto So no problem if it's known, thanks!

**Comment by leto** [comment]
Thanks for the bug report, we appreciate them! :+1:
