### ISSUE TITLE
Delete references to the z-board.net website

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragon#57]
I see a lot of internet link to z-board.net website

I think we can delete the old code.
Example :
1) In all translate '.ts' :
 <location filename="../src/zboard.ui" line="85"/>
<source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;ZBoard: Fully anonymous and untraceable chat messages based on the ZCash blockchain. &lt;a href=&quot;http://www.z-board.net/&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;http://www.z-board.net/&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
       
2) In the 'src'  :
zboard.ui

3) In all translate '.ts' :
<location filename="../src/zboard.ui" line="14"/>
<source>Post to z-board.net</source>
<translation>Poster sur z-board.net</translation>

**Comment by leto** [comment]
@gilardh i removed zboard so we can remove all zboard translation stuff
