### ISSUE TITLE
In dark mode, mobile app connection string is white-on-white text

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragon#88]
It's visible when selected but otherwise invisible

**Comment by csharpee** [comment]
This doesn't not occur for me. 

![Screenshot from 2020-04-25 20-40-45](https://user-images.githubusercontent.com/18726788/80294233-42165e00-8735-11ea-8a14-b866665c3a65.png)

**Comment by leto** [comment]
@csharpee this bug went away, :tada:
