### ISSUE TITLE
Silent Dragon v0.8.2 Issue Finding Params

### ISSUE THREAD

**Issue by RunningManTheG** [MyHush/SilentDragon#97]
I am running into an issue using Silent Dragon Application on Mac OS (10.14.3 Mojave). Below are the steps I have taken and where I run into this issue.

Step 1: Downloaded SilentDragon v0.8.2-mac.dmg from Github (re https://github.com/MyHush/SilentDragon/releases)

Step 2: Open/unzip SilentDragon-0.8.2-mac.dmg which creates shortcut App "silentdragon"

Step 3: Copy Application shortcut to application folder

Step 4: Double click "silentdragon" app shortcut to open application. 

Step 5: ISSUE-- Silent Dragon wallet opens but error message appears stating "Couldn't download params. Please check the help site for more info" (See picture attached)
![Screen Shot 2019-11-15 at 4 17 03 PM](https://user-images.githubusercontent.com/57814693/68976542-fba2f780-07c3-11ea-951d-81b30e5ba0a6.png)

*When I right click the app shortcut and hit "Show Package Contents" There are 4 folders (Frameworks, MacOS, PlugIns, Resources). When I click on "MacOS" I can see what look like some sort of .txt files that are labelled "sapling-output.params" and "sapling-send.params"
![Screen Shot 2019-11-15 at 3 58 40 PM](https://user-images.githubusercontent.com/57814693/68976558-02ca0580-07c4-11ea-94e8-81f8a943bf0b.png)

I am assuming these are the Sapling Params needed to run silent dragon, but for some reason the application can not find them and use them. Any help is appreciated

**Comment by leto** [comment]
@RunningManTheG nicely written bug report and thanks :+1:

**Comment by leto** [comment]
Potential fix in `duke` branch now, waiting on testing from @radix42

**Comment by leto** [comment]
I was told this was fixed, we can re-open if not
